FROM postgres:latest

# Install PostGIS and osm2pgsql
RUN apt-get update && \
    apt-get install -y postgis postgresql-13-postgis-3 curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add the PostGIS extension to the default database
COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/
