FROM postgres:latest

# Install PostGIS
RUN apt-get update && \
    apt-get install -y postgis postgresql-13-postgis-3 osm2pgsql curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add the PostGIS extension to the default database
RUN docker-entrypoint.sh postgres & \
    until pg_isready; do \
        sleep 1; \
    done && \
    psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE EXTENSION postgis;"
